#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="/home/sage/ELEN20006_Labs/Project/fpga-digital-watch"

mkdir -p "$PROJECT_DIR/waveform_svgs"

python vcd_render.py wave_arming_latch.vcd output.svg --signals wave_arming_latch.clk wave_arming_latch.arm wave_arming_latch.disarm wave_arming_latch.armed --clk wave_arming_latch.clk --out waveform_svgs/wave_arming_latch.svg

python vcd_render.py wave_binary_to_bcd.vcd output.svg --signals wave_binary_to_bcd.bin[6:0] wave_binary_to_bcd.tens[3:0] wave_binary_to_bcd.ones[3:0] --dec wave_binary_to_bcd.bin[6:0] wave_binary_to_bcd.tens[3:0] wave_binary_to_bcd.ones[3:0] --out waveform_svgs/wave_binary_to_bcd.svg

python vcd_render.py wave_button_auto_repeat.vcd output.svg --signals wave_button_auto_repeat.clk wave_button_auto_repeat.button wave_button_auto_repeat.pulse --clk wave_button_auto_repeat.clk --out waveform_svgs/wave_button_auto_repeat.svg

python vcd_render.py wave_button_hold_detect.vcd output.svg --signals wave_button_hold_detect.clk wave_button_hold_detect.button wave_button_hold_detect.held --clk wave_button_hold_detect.clk --out waveform_svgs/wave_button_hold_detect.svg

python vcd_render.py wave_button_hold_pulse.vcd output.svg --signals wave_button_hold_pulse.clk wave_button_hold_pulse.button wave_button_hold_pulse.pulse --clk wave_button_hold_pulse.clk --out waveform_svgs/wave_button_hold_pulse.svg

python vcd_render.py wave_decimal_display_driver.vcd output.svg --signals wave_decimal_display_driver.value0[6:0] wave_decimal_display_driver.blank0 wave_decimal_display_driver.HEX0[6:0] wave_decimal_display_driver.value1[6:0] wave_decimal_display_driver.blank1 wave_decimal_display_driver.HEX1[6:0] wave_decimal_display_driver.value2[6:0] wave_decimal_display_driver.blank2 wave_decimal_display_driver.HEX2[6:0] wave_decimal_display_driver.HEX3[6:0] wave_decimal_display_driver.HEX4[6:0] wave_decimal_display_driver.HEX5[6:0] --dec wave_decimal_display_driver.value0[6:0] wave_decimal_display_driver.value1[6:0] wave_decimal_display_driver.value2[6:0] --bin wave_decimal_display_driver.HEX0[6:0] wave_decimal_display_driver.HEX1[6:0] wave_decimal_display_driver.HEX2[6:0] wave_decimal_display_driver.HEX3[6:0] wave_decimal_display_driver.HEX4[6:0] wave_decimal_display_driver.HEX5[6:0] --out waveform_svgs/wave_decimal_display_driver.svg

python vcd_render.py wave_edit_mode_selector.vcd output.svg --signals wave_edit_mode_selector.clk wave_edit_mode_selector.button wave_edit_mode_selector.mode_enable[2:0] --clk wave_edit_mode_selector.clk --bin wave_edit_mode_selector.mode_enable[2:0] --out waveform_svgs/wave_edit_mode_selector.svg

python vcd_render.py wave_editable_counter.vcd output.svg --signals wave_editable_counter.clk wave_editable_counter.tick wave_editable_counter.edit_mode wave_editable_counter.inc wave_editable_counter.dec wave_editable_counter.count[1:0] --clk wave_editable_counter.clk --dec wave_editable_counter.count[1:0] --out waveform_svgs/wave_editable_counter.svg

python vcd_render.py wave_hms_counter.vcd output.svg --signals wave_hms_counter.clk wave_hms_counter.enable wave_hms_counter.hours[1:0] wave_hms_counter.minutes[1:0] wave_hms_counter.seconds[2:0] --clk wave_hms_counter.clk --dec wave_hms_counter.hours[1:0] wave_hms_counter.minutes[1:0] wave_hms_counter.seconds[2:0] --out waveform_svgs/wave_hms_counter.svg

python vcd_render.py wave_key_synchroniser.vcd output.svg --signals wave_key_synchroniser.clk wave_key_synchroniser.key_n[3:0] wave_key_synchroniser.key_sync[3:0] --clk wave_key_synchroniser.clk --bin wave_key_synchroniser.key_n[3:0] wave_key_synchroniser.key_sync[3:0] --out waveform_svgs/wave_key_synchroniser.svg

python vcd_render.py wave_mod_n_counter.vcd output.svg --signals wave_mod_n_counter.clk wave_mod_n_counter.enable wave_mod_n_counter.rst wave_mod_n_counter.count[2:0] --clk wave_mod_n_counter.clk --dec wave_mod_n_counter.count[2:0] --out waveform_svgs/wave_mod_n_counter.svg

python vcd_render.py wave_pwm_generator.vcd output.svg --signals wave_pwm_generator.clk wave_pwm_generator.rst wave_pwm_generator.pwm_out --clk wave_pwm_generator.clk --out waveform_svgs/wave_pwm_generator.svg

python vcd_render.py wave_restartable_rate_generator.vcd output.svg --signals wave_restartable_rate_generator.clk wave_restartable_rate_generator.run wave_restartable_rate_generator.tick --clk wave_restartable_rate_generator.clk --out waveform_svgs/wave_restartable_rate_generator.svg

python vcd_render.py wave_rising_edge_detector.vcd output.svg --signals wave_rising_edge_detector.clk wave_rising_edge_detector.sig_in wave_rising_edge_detector.rise --clk wave_rising_edge_detector.clk --out waveform_svgs/wave_rising_edge_detector.svg

python vcd_render.py wave_seven_segment.vcd output.svg --signals wave_seven_segment.blank wave_seven_segment.digit[3:0] wave_seven_segment.segments[6:0] --dec wave_seven_segment.digit[3:0] --bin wave_seven_segment.segments[6:0] --out waveform_svgs/wave_seven_segment.svg

# Includes selected DUT time internals because top-level ports expose only switch/display pins, not the actual counter values.
python vcd_render.py wave_top_time_display_v1.vcd output.svg --signals wave_top_time_display_v1.clk wave_top_time_display_v1.SW[1:0] wave_top_time_display_v1.dut.tick_1hz wave_top_time_display_v1.dut.tick_25hz wave_top_time_display_v1.dut.tick_1khz wave_top_time_display_v1.dut.hours[4:0] wave_top_time_display_v1.dut.minutes[5:0] wave_top_time_display_v1.dut.seconds[5:0] wave_top_time_display_v1.HEX5[6:0] wave_top_time_display_v1.HEX4[6:0] wave_top_time_display_v1.HEX3[6:0] wave_top_time_display_v1.HEX2[6:0] wave_top_time_display_v1.HEX1[6:0] wave_top_time_display_v1.HEX0[6:0] --clk wave_top_time_display_v1.clk --dec wave_top_time_display_v1.dut.hours[4:0] wave_top_time_display_v1.dut.minutes[5:0] wave_top_time_display_v1.dut.seconds[5:0] --bin wave_top_time_display_v1.SW[1:0] wave_top_time_display_v1.HEX5[6:0] wave_top_time_display_v1.HEX4[6:0] wave_top_time_display_v1.HEX3[6:0] wave_top_time_display_v1.HEX2[6:0] wave_top_time_display_v1.HEX1[6:0] wave_top_time_display_v1.HEX0[6:0] --out waveform_svgs/wave_top_time_display_v1.svg

python vcd_render.py wave_up_down_counter.vcd output.svg --signals wave_up_down_counter.clk wave_up_down_counter.enable wave_up_down_counter.up wave_up_down_counter.count[2:0] --clk wave_up_down_counter.clk --dec wave_up_down_counter.count[2:0] --out waveform_svgs/wave_up_down_counter.svg

# Includes selected DUT time/edit internals because top-level display buses do not show the underlying hour/minute/second counters.
python vcd_render.py wave_user_top_watch_v1.vcd output.svg --signals wave_user_top_watch_v1.clk wave_user_top_watch_v1.button[3:0] wave_user_top_watch_v1.sw[9:0] wave_user_top_watch_v1.dut.seconds_tick wave_user_top_watch_v1.dut.minutes_tick wave_user_top_watch_v1.dut.hours_tick wave_user_top_watch_v1.dut.hours_edit wave_user_top_watch_v1.dut.minutes_edit wave_user_top_watch_v1.dut.seconds_edit wave_user_top_watch_v1.dut.hours[4:0] wave_user_top_watch_v1.hours_disp[6:0] wave_user_top_watch_v1.dut.minutes[5:0] wave_user_top_watch_v1.minutes_disp[6:0] wave_user_top_watch_v1.dut.seconds[5:0] wave_user_top_watch_v1.seconds_disp[6:0] wave_user_top_watch_v1.blank_hours wave_user_top_watch_v1.blank_minutes wave_user_top_watch_v1.blank_seconds wave_user_top_watch_v1.led[9:0] --clk wave_user_top_watch_v1.clk --dec wave_user_top_watch_v1.dut.hours[4:0] wave_user_top_watch_v1.hours_disp[6:0] wave_user_top_watch_v1.dut.minutes[5:0] wave_user_top_watch_v1.minutes_disp[6:0] wave_user_top_watch_v1.dut.seconds[5:0] wave_user_top_watch_v1.seconds_disp[6:0] --bin wave_user_top_watch_v1.button[3:0] wave_user_top_watch_v1.sw[9:0] wave_user_top_watch_v1.led[9:0] --out waveform_svgs/wave_user_top_watch_v1.svg

# Includes selected DUT mode/PWM/time internals to show edit-mode selection and flashing behavior alongside grouped display outputs.
python vcd_render.py wave_user_top_watch_v2.vcd output.svg --signals wave_user_top_watch_v2.clk wave_user_top_watch_v2.button[3:0] wave_user_top_watch_v2.sw[9:0] wave_user_top_watch_v2.dut.mode_enable[2:0] wave_user_top_watch_v2.dut.pwm_out wave_user_top_watch_v2.dut.seconds_tick wave_user_top_watch_v2.dut.minutes_tick wave_user_top_watch_v2.dut.hours_tick wave_user_top_watch_v2.dut.hours_edit wave_user_top_watch_v2.dut.minutes_edit wave_user_top_watch_v2.dut.seconds_edit wave_user_top_watch_v2.dut.hours[4:0] wave_user_top_watch_v2.hours_disp[6:0] wave_user_top_watch_v2.dut.minutes[5:0] wave_user_top_watch_v2.minutes_disp[6:0] wave_user_top_watch_v2.dut.seconds[5:0] wave_user_top_watch_v2.seconds_disp[6:0] wave_user_top_watch_v2.blank_hours wave_user_top_watch_v2.blank_minutes wave_user_top_watch_v2.blank_seconds wave_user_top_watch_v2.led[9:0] --clk wave_user_top_watch_v2.clk --dec wave_user_top_watch_v2.dut.hours[4:0] wave_user_top_watch_v2.hours_disp[6:0] wave_user_top_watch_v2.dut.minutes[5:0] wave_user_top_watch_v2.minutes_disp[6:0] wave_user_top_watch_v2.dut.seconds[5:0] wave_user_top_watch_v2.seconds_disp[6:0] --bin wave_user_top_watch_v2.button[3:0] wave_user_top_watch_v2.sw[9:0] wave_user_top_watch_v2.dut.mode_enable[2:0] wave_user_top_watch_v2.led[9:0] --out waveform_svgs/wave_user_top_watch_v2.svg

# Includes selected DUT event/mode/time internals to show auto-repeat increment/decrement inputs and their effect on grouped time displays.
python vcd_render.py wave_user_top_watch_v3.vcd output.svg --signals wave_user_top_watch_v3.clk wave_user_top_watch_v3.button[3:0] wave_user_top_watch_v3.sw[9:0] wave_user_top_watch_v3.dut.inc_event wave_user_top_watch_v3.dut.dec_event wave_user_top_watch_v3.dut.mode_enable[2:0] wave_user_top_watch_v3.dut.pwm_out wave_user_top_watch_v3.dut.seconds_tick wave_user_top_watch_v3.dut.minutes_tick wave_user_top_watch_v3.dut.hours_tick wave_user_top_watch_v3.dut.hours_inc wave_user_top_watch_v3.dut.hours_dec wave_user_top_watch_v3.dut.hours_edit wave_user_top_watch_v3.dut.minutes_inc wave_user_top_watch_v3.dut.minutes_dec wave_user_top_watch_v3.dut.minutes_edit wave_user_top_watch_v3.dut.seconds_inc wave_user_top_watch_v3.dut.seconds_dec wave_user_top_watch_v3.dut.seconds_edit wave_user_top_watch_v3.dut.hours[4:0] wave_user_top_watch_v3.hours_disp[6:0] wave_user_top_watch_v3.dut.minutes[5:0] wave_user_top_watch_v3.minutes_disp[6:0] wave_user_top_watch_v3.dut.seconds[5:0] wave_user_top_watch_v3.seconds_disp[6:0] wave_user_top_watch_v3.blank_hours wave_user_top_watch_v3.blank_minutes wave_user_top_watch_v3.blank_seconds wave_user_top_watch_v3.led[9:0] --clk wave_user_top_watch_v3.clk --dec wave_user_top_watch_v3.dut.hours[4:0] wave_user_top_watch_v3.hours_disp[6:0] wave_user_top_watch_v3.dut.minutes[5:0] wave_user_top_watch_v3.minutes_disp[6:0] wave_user_top_watch_v3.dut.seconds[5:0] wave_user_top_watch_v3.seconds_disp[6:0] --bin wave_user_top_watch_v3.button[3:0] wave_user_top_watch_v3.sw[9:0] wave_user_top_watch_v3.dut.mode_enable[2:0] wave_user_top_watch_v3.led[9:0] --out waveform_svgs/wave_user_top_watch_v3.svg

# Includes selected DUT reset/event/mode/time internals to show seconds reset and edit behavior alongside grouped display outputs.
python vcd_render.py wave_user_top_watch_v4.vcd output.svg --signals wave_user_top_watch_v4.clk wave_user_top_watch_v4.button[3:0] wave_user_top_watch_v4.sw[9:0] wave_user_top_watch_v4.dut.inc_event wave_user_top_watch_v4.dut.dec_event wave_user_top_watch_v4.dut.rst_seconds wave_user_top_watch_v4.dut.mode_enable[2:0] wave_user_top_watch_v4.dut.pwm_out wave_user_top_watch_v4.dut.seconds_tick wave_user_top_watch_v4.dut.minutes_tick wave_user_top_watch_v4.dut.hours_tick wave_user_top_watch_v4.dut.hours_inc wave_user_top_watch_v4.dut.hours_dec wave_user_top_watch_v4.dut.hours_edit wave_user_top_watch_v4.dut.minutes_inc wave_user_top_watch_v4.dut.minutes_dec wave_user_top_watch_v4.dut.minutes_edit wave_user_top_watch_v4.dut.seconds_inc wave_user_top_watch_v4.dut.seconds_dec wave_user_top_watch_v4.dut.seconds_edit wave_user_top_watch_v4.dut.hours[4:0] wave_user_top_watch_v4.hours_disp[6:0] wave_user_top_watch_v4.dut.minutes[5:0] wave_user_top_watch_v4.minutes_disp[6:0] wave_user_top_watch_v4.dut.seconds[5:0] wave_user_top_watch_v4.seconds_disp[6:0] wave_user_top_watch_v4.blank_hours wave_user_top_watch_v4.blank_minutes wave_user_top_watch_v4.blank_seconds wave_user_top_watch_v4.led[9:0] --clk wave_user_top_watch_v4.clk --dec wave_user_top_watch_v4.dut.hours[4:0] wave_user_top_watch_v4.hours_disp[6:0] wave_user_top_watch_v4.dut.minutes[5:0] wave_user_top_watch_v4.minutes_disp[6:0] wave_user_top_watch_v4.dut.seconds[5:0] wave_user_top_watch_v4.seconds_disp[6:0] --bin wave_user_top_watch_v4.button[3:0] wave_user_top_watch_v4.sw[9:0] wave_user_top_watch_v4.dut.mode_enable[2:0] wave_user_top_watch_v4.led[9:0] --out waveform_svgs/wave_user_top_watch_v4.svg
